# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "ad128ec106a47335e9e98801f0251948"
name = "swoo-roomnhoom-app"
handle = "swoo-roomnhoom-app"
application_url = "https://machine-poem-boulevard-cook.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "swooapp.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_orders,read_products"

[auth]
redirect_urls = [
  "https://machine-poem-boulevard-cook.trycloudflare.com/auth/callback",
  "https://machine-poem-boulevard-cook.trycloudflare.com/auth/shopify/callback",
  "https://machine-poem-boulevard-cook.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
