# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "ad128ec106a47335e9e98801f0251948"
name = "swoo-roomnhoom-app"
handle = "swoo-roomnhoom-app"
application_url = "https://wicked-meets-unnecessary-considered.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://wicked-meets-unnecessary-considered.trycloudflare.com/auth/callback",
  "https://wicked-meets-unnecessary-considered.trycloudflare.com/auth/shopify/callback",
  "https://wicked-meets-unnecessary-considered.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
